### ISSUE TITLE
my ears hurt

### ISSUE THREAD

**Issue by marczeugs** [HumanoidSandvichDispenser/SupaLidlGame#5]
please replace the railgun sound with one that doesn't rupture my eardrums <img src="https://cdn.betterttv.net/emote/5ad22a7096065b6c6bddf7f3/3x.webp" width="28" height="28"/>

**Comment by HumanoidSandvichDispenser** [comment]
the railgun weapon isn't supposed to have any sound and it's a test weapon anyways so i guess you must be talking about this thing?

![image](https://github.com/HumanoidSandvichDispenser/SupaLidlGame/assets/25856867/4711d879-c746-4cb4-be36-4630ec07f793)

**Comment by marczeugs** [comment]
oh yeah, i mean the shotgun. i got confused because it seems to fire the `RailBeam` projectile if my eyes do not deceive me. understanding how the files are related is hard when you don't know godot and are highly regarded like me <img src="https://cdn.frankerfacez.com/emoticon/536927/4" height="28"/><img src="https://cdn.betterttv.net/emote/5c6ab708adab351034b4050f/3x.webp" height="28"/>

**Comment by HumanoidSandvichDispenser** [comment]
i don't blame you because this is my first time using godot, and this is the result of a year of trying everything until it works, so much so that i asked someone if they wanted to work on this, but he just said no and left ![image](https://github.com/HumanoidSandvichDispenser/SupaLidlGame/assets/25856867/ab3b4529-4c7b-4869-917c-6232719e52c9)
